vich_uploader:
    db_driver: orm

    mappings:
        passport:
           uri_prefix: /images/candidates/passport
           upload_destination: '%kernel.project_dir%/public/images/passport'
           
            # inject_on_load: 'false'
            # delete_on_update: 'true'
            # delete_on_remove: 'true'
